=== Engerim/rmf-codegen/ctp-validators/src/main/resources/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ruleset" type="rulesetType"/>
  <xs:complexType name="optionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="optionsType">
    <xs:sequence>
      <xs:element type="optionType" name="option" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ruleType">
    <xs:all>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="optionsType" name="options" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="rulesType">
    <xs:sequence>
      <xs:element type="ruleType" name="rule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="rulesetType">
    <xs:all>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="rulesType" name="rules"  minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== Engerim/rmf-codegen/ctp-validators/src/main/resources/ruleset.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ruleset.xsd">
    <name>default</name>
    <rules>
        <rule>
            <name>com.commercetools.rmf.validators.PluralRule</name>
            <options>
                <option type="exclude">in-store</option>
                <option type="exclude">me</option>
                <option type="exclude">inventory</option>
                <option type="exclude">login</option>
                <option type="exclude">import</option>
                <option type="exclude">password</option>
                <option type="exclude">reset</option>
                <option type="exclude">confirm</option>
            </options>
        </rule>
        <rule>
            <name>com.commercetools.rmf.validators.CamelCaseRule</name>
        </rule>
    </rules>
</ruleset>
